# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1797f938b91b86e4af59d214fa53fa2aff1f5cc973e9e1a32ff01be0273b70de37b85f4991fb97700dd74654eea8d39a1eb4627e63ebbf722984ce0f1574bf58

test:
  secret_key_base: 8851a860bffd396372a6eec384606a0dff222ad50a2eb77e0848003365310738b9d51e9546b3beb19a92107c0aa3960cdce40387daed14f099af8d8c195f3cd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
